# Generated by Django 4.1.2 on 2022-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporaEntityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_period', models.CharField(max_length=50)),
                ('category', models.TextField()),
                ('avg_sentence_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('author', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('time_period', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('file', models.FileField(upload_to='texts/')),
                ('avg_sentence_length', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
