# Generated by Django 4.1.2 on 2022-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('time_period', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='texts/')),
                ('avg_sentence_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_period', models.CharField(max_length=50)),
                ('text_type', models.TextField()),
                ('avg_sentence_length', models.IntegerField()),
            ],
        ),
    ]
