# Generated by Django 4.1.2 on 2022-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textura_app', '0002_uploadedtext_avg_sentence_length_stdev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedtext',
            name='avg_word_length',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uploadedtext',
            name='avg_word_length_stdev',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
