# Generated by Django 4.1.2 on 2022-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textura_app', '0003_uploadedtext_avg_word_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedtext',
            name='avg_sentence_length_rank',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='corporaentitydata',
            name='avg_sentence_length',
            field=models.FloatField(),
        ),
    ]
