# Generated by Django 4.1.2 on 2022-11-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textura_app', '0004_uploadedtext_avg_sentence_length_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporaentitydata',
            name='avg_word_length',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uploadedtext',
            name='avg_word_length_rank',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='corporaentitydata',
            name='avg_sentence_length',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
